version: "3.9"
services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: postgres
volumes:
  redis:
    driver: local
